### ISSUE TITLE
Help Please Garret

### ISSUE THREAD

**Issue by Invinso1** [MineSworn/SwornNations#1]
I got a name change. On minesworn, it says I no longer own my faction "NKorea" but when I try to join, MY SCREEN says "KIM_JONG_UNVINSO tried to join your faction" but when I try to invite myself, it says "you are not a member of any faction." So I own my facton, but don't at the same time. Can you please make KIM_JONG_UNVINSO admin of NKorea and remove invinso1's account from the server database or something? I heard that TRUE had the same issue. Thanks for helping.

**Comment by dmulloy2** [comment]
Sorted
