### ISSUE TITLE
Feature request: Option to disable SwornNations tpa

### ISSUE THREAD

**Issue by AnIronGolem** [MineSworn/SwornNations#3]
Garret is going to enable global tpa but we need to disable the SwornNations tpa first.

**Comment by dmulloy2** [comment]
I gotta say I'm against it mostly because I've been raided thru tpa before, but it won't be difficult to add a toggle.

**Comment by dmulloy2** [comment]
A toggle already exists. Just remove all the commands from the ownTerritoryOnlyCommands section of the conf.json.
